language: bash
services: docker
fast_finish: true
env:
    # Oracle jobs have been removed because there aren't public images anymore.
    # phpunit
    # PostgreSQL highest, lowest php supported
    # We have set the "phpunit-full" to run against master.
    - "PHP=7.3 DB=pgsql   GIT=master SUITE=phpunit-full"
    - "PHP=7.2 DB=pgsql   GIT=master SUITE=phpunit-full"
    # Simpler "phpunit" for stables
    - "PHP=7.3 DB=pgsql   GIT=v3.8.0 SUITE=phpunit"
    - "PHP=7.1 DB=pgsql   GIT=v3.8.0 SUITE=phpunit"
    - "PHP=7.3 DB=pgsql   GIT=v3.7.2 SUITE=phpunit"
    - "PHP=7.1 DB=pgsql   GIT=v3.7.2 SUITE=phpunit"
    - "PHP=7.2 DB=pgsql   GIT=v3.5.8 SUITE=phpunit"
    - "PHP=7.0 DB=pgsql   GIT=v3.5.8 SUITE=phpunit"
    # Other databases, only highest php supported
    - "PHP=7.3 DB=mssql   GIT=v3.8.0 SUITE=phpunit"
    - "PHP=7.3 DB=mssql   GIT=v3.7.2 SUITE=phpunit"
    - "PHP=7.2 DB=mssql   GIT=v3.5.8 SUITE=phpunit"
    - "PHP=7.3 DB=mysql   GIT=v3.8.0 SUITE=phpunit"
    - "PHP=7.3 DB=mysql   GIT=v3.7.2 SUITE=phpunit"
    - "PHP=7.2 DB=mysql   GIT=v3.5.8 SUITE=phpunit"
    # MariaDB, only lowest php supported
    - "PHP=7.1 DB=mariadb GIT=v3.8.0 SUITE=phpunit"
    - "PHP=7.1 DB=mariadb GIT=v3.7.2 SUITE=phpunit"
    - "PHP=7.0 DB=mariadb GIT=v3.5.8 SUITE=phpunit"
    # behat
    # PostgreSQL highest, lowest (2 browsers)
    - "PHP=7.3 DB=pgsql   GIT=master SUITE=behat BROWSER=chrome"
    - "PHP=7.3 DB=pgsql   GIT=master SUITE=behat BROWSER=firefox"
    - "PHP=7.2 DB=pgsql   GIT=master SUITE=behat BROWSER=chrome"
    - "PHP=7.2 DB=pgsql   GIT=master SUITE=behat BROWSER=firefox"
    - "PHP=7.3 DB=pgsql   GIT=v3.8.0 SUITE=behat BROWSER=chrome"
    - "PHP=7.3 DB=pgsql   GIT=v3.8.0 SUITE=behat BROWSER=firefox"
    - "PHP=7.1 DB=pgsql   GIT=v3.8.0 SUITE=behat BROWSER=chrome"
    - "PHP=7.1 DB=pgsql   GIT=v3.8.0 SUITE=behat BROWSER=firefox"
    - "PHP=7.3 DB=pgsql   GIT=v3.7.2 SUITE=behat BROWSER=chrome"
    - "PHP=7.3 DB=pgsql   GIT=v3.7.2 SUITE=behat BROWSER=firefox"
    - "PHP=7.1 DB=pgsql   GIT=v3.7.2 SUITE=behat BROWSER=chrome"
    - "PHP=7.1 DB=pgsql   GIT=v3.7.2 SUITE=behat BROWSER=firefox"
    - "PHP=7.2 DB=pgsql   GIT=v3.5.8 SUITE=behat BROWSER=chrome"
    - "PHP=7.2 DB=pgsql   GIT=v3.5.8 SUITE=behat BROWSER=firefox"
    - "PHP=7.0 DB=pgsql   GIT=v3.5.8 SUITE=behat BROWSER=chrome"
    - "PHP=7.0 DB=pgsql   GIT=v3.5.8 SUITE=behat BROWSER=firefox"
    # Other databases, only highest php supported (1 browsers)
    - "PHP=7.3 DB=mssql   GIT=v3.8.0 SUITE=behat BROWSER=firefox" # Other databases, only highest php supported (1 browsers)
    - "PHP=7.3 DB=mssql   GIT=v3.7.2 SUITE=behat BROWSER=chrome"
    - "PHP=7.2 DB=mssql   GIT=v3.5.8 SUITE=behat BROWSER=firefox"
    - "PHP=7.3 DB=mysql   GIT=v3.8.0 SUITE=behat BROWSER=chrome"
    - "PHP=7.3 DB=mysql   GIT=v3.7.2 SUITE=behat BROWSER=chrome"
    - "PHP=7.2 DB=mysql   GIT=v3.5.8 SUITE=behat BROWSER=firefox"
    # MariaDB, only lowest php supported (1 browsers)
    - "PHP=7.1 DB=mariadb GIT=v3.8.0 SUITE=behat BROWSER=firefox"
    - "PHP=7.1 DB=mariadb GIT=v3.7.2 SUITE=behat BROWSER=chrome"
    - "PHP=7.0 DB=mariadb GIT=v3.5.8 SUITE=behat BROWSER=firefox"
    # Mobile app
    - "PHP=7.3 DB=pgsql GIT=master SUITE=app BROWSER=chrome MOBILE=next"
    - "PHP=7.3 DB=pgsql GIT=master SUITE=app BROWSER=chrome MOBILE=latest"
install:
    - git clone --branch $GIT --depth 1 git://github.com/moodle/moodle $HOME/moodle
    - cp config.docker-template.php $HOME/moodle/config.php
    - export MOODLE_DOCKER_DB=$DB
    - export MOODLE_DOCKER_BROWSER=$BROWSER
    - export MOODLE_DOCKER_WWWROOT="$HOME/moodle"
    - export MOODLE_DOCKER_PHP_VERSION=$PHP
    - export MOODLE_APP_VERSION=$MOBILE
before_script:
    - tests/setup.sh
script:
    - tests/test.sh
after_script:
    - bin/moodle-docker-compose down
